Sidebar/Controllers/ExamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sidebar.Data;
using Sidebar.Dtos;
using Sidebar.Models;
using Sidebar.Services;

namespace Sidebar.Controllers
{
    public class ExamsController : Controller
    {
        private readonly WebAppDbContext _db;
        private readonly ExamService _service;        

        public ExamsController(WebAppDbContext context, ExamService service)
        {
            _db = context;
            _service = service;
        }
        //private readonly WebAppDbContext _context;

        //public ExamsController(WebAppDbContext context)
        //{
        //    _context = context;
        //}

        // GET: Exams

        [HttpGet]
        [ProducesResponseType(typeof(ExamDto), 200)]
        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAll());
        }
        //public async Task<IActionResult> Index()
        //{

        //    return View(await _context.Exams.ToListAsync());
        //}

        // GET: Exams/Details/5
        [HttpGet]
        [ProducesResponseType(typeof(ExamDto), 200)]
        public async Task<IActionResult> Details(int id)
        {
            MyDTO myDTO = await _service.Get(id);
            ViewBag.Message = myDTO.Message;
            if (myDTO.View == "Index")
            {
                return View($"{myDTO.View}", myDTO.ExamDtos);
            }
            return View($"{myDTO.View}", myDTO.ExamDto);
        }
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null || _context.Exams == null)
        //    {
        //        return NotFound();
        //    }

        //    var exam = await _context.Exams
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (exam == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(exam);
        //}

        // GET: Exams/Create
        [HttpGet]
        [ProducesResponseType(typeof(ExamDto), 200)]
        public IActionResult Create()
        {
            ViewBag.Candidates = new SelectList(_db.Candidates, "Id", "Id");
            ViewBag.Certificates = new SelectList(_db.Certificates, "TitleOfCertificate", "TitleOfCertificate");
            return View();
        }
        //public IActionResult Create()
        //{
        //    ViewBag.Certificates = new SelectList(_context.Certificates, "Id", "TitleOfCertificate");
        //    ViewBag.Candidates = new SelectList(_context.Candidates, "Id", "LastName");
        //    return View();
        //}

        // POST: Exams/Create
        [HttpPost]
        [ProducesResponseType(typeof(ExamDto), 200)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("Id,AssessmentTestCode,ExaminationDate,ScoreReportDate," +
            "CandidateScore,PercentageScore,AssessmentResultLabel,CandidateId,Candidate,TitleOfCertificate,Certificate")] ExamDto examDto)
        {
            MyDTO myDTO = await _service.AddOrUpdate(id, examDto);
            ViewBag.Message = myDTO.Message;
            if (myDTO.View == "Index")
            {
                return View($"{myDTO.View}", myDTO.ExamDtos);
            }
            ViewBag.Candidates = new SelectList(_db.Candidates, "Id", "Id");
            ViewBag.Certificates = new SelectList(_db.Certificates, "TitleOfCertificate", "TitleOfCertificate");
            return View($"{myDTO.View}", myDTO.ExamDto);
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("assessmentTestCode, CertificateId, CandidateId")] ExamCreateDTO examDTO)
        //{
        //    if (ModelState.IsValid) {
        //        Certificate certificate = _context.Certificates.Find(examDTO.CertificateId);
        //        Candidate candidate = _context.Candidates.Find(examDTO.CandidateId);
        //        Exam exam = new Exam(examDTO.assessmentTestCode, certificate, candidate);
        //        _context.Add(exam);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction("TakeExam", "ExamStems", new { id = exam.Id });
        //    }
        //    return View(examDTO);
        //}

        // GET: Exams/Edit/5
        [HttpGet]
        [ProducesResponseType(typeof(ExamDto), 200)]
        public async Task<IActionResult> Edit(int id)
        {
            MyDTO myDTO = await _service.GetForUpdate(id);
            ViewBag.Message = myDTO.Message;
            ViewBag.Candidates = new SelectList(_db.Candidates, "Id", "Id");
            ViewBag.Certificates = new SelectList(_db.Certificates, "TitleOfCertificate", "TitleOfCertificate");
            if (myDTO.View == "Index")
            {
                return View($"{myDTO.View}", myDTO.ExamDtos);
            }
            return View($"{myDTO.View}", myDTO.ExamDto);
        }
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null || _context.Exams == null)
        //    {
        //        return NotFound();
        //    }

        //    var exam = await _context.Exams.FindAsync(id);
        //    ViewBag.Certificates = new SelectList(_context.Certificates, "Id", "TitleOfCertificate");
        //    ViewBag.Candidates = new SelectList(_context.Candidates, "Id", "LastName");
        //    if (exam == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(exam);
        //}

        // POST: Exams/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ProducesResponseType(typeof(ExamDto), 200)]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AssessmentTestCode,ExaminationDate,ScoreReportDate," +
            "CandidateScore,PercentageScore,AssessmentResultLabel,CandidateId,Candidate,TitleOfCertificate,Certificate")] ExamDto examDto)
        {
            MyDTO myDTO = await _service.AddOrUpdate(id, examDto);
            ViewBag.Message = myDTO.Message;
            if (myDTO.View == "Index")
            {
                return View($"{myDTO.View}", myDTO.ExamDtos);
            }
            ViewBag.Candidates = new SelectList(_db.Candidates, "Id", "Id");
            ViewBag.Certificates = new SelectList(_db.Certificates, "TitleOfCertificate", "TitleOfCertificate");
            return View($"{myDTO.View}", myDTO.ExamDto);
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,AssessmentTestCode,ExaminationDate,ScoreReportDate,CandidateScore,PercentageScore,AssessmentResultLabel")] Exam exam)
        //{
        //    if (id != exam.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(exam);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!ExamExists(exam.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(exam);
        //}

        // GET: Exams/Delete/5
        [HttpGet]
        [ProducesResponseType(typeof(ExamDto), 200)]
        public async Task<IActionResult> Delete(int id)
        {
            MyDTO myDTO = await _service.GetForDelete(id);
            ViewBag.Message = myDTO.Message;
            if (myDTO.View == "Index")
            {
                return View($"{myDTO.View}", myDTO.ExamDtos);
            }
            return View($"{myDTO.View}", myDTO.ExamDto);
        }
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null || _context.Exams == null)
        //    {
        //        return NotFound();
        //    }

        //    var exam = await _context.Exams
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (exam == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(exam);
        //}

        // POST: Exams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [ProducesResponseType(typeof(ExamDto), 200)]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            MyDTO myDTO = await _service.Delete(id);
            ViewBag.Message = myDTO.Message;
            return View($"{myDTO.View}", myDTO.ExamDtos);
        }

        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    if (_context.Exams == null)
        //    {
        //        return Problem("Entity set 'WebAppDbContext.Exams'  is null.");
        //    }
        //    var exam = await _context.Exams.FindAsync(id);
        //    if (exam != null)
        //    {
        //        _context.Exams.Remove(exam);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool ExamExists(int id)
        //{
        //    return _context.Exams.Any(e => e.Id == id);
        //}
    }
}

Sidebar/Controllers/StemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sidebar.Data;
using Sidebar.Dtos;
using Sidebar.Models;
using Sidebar.Services;

namespace Sidebar.Controllers {
    public class StemsController : Controller 
    {
        private readonly WebAppDbContext _db;
        private readonly TopicService _topicService;
        private readonly StemService _service;
        private readonly IWebHostEnvironment _webHostEnvironment;
        
        public StemsController(WebAppDbContext db, TopicService topicService, 
            StemService service, IWebHostEnvironment webHostEnvironment) 
        {
            _db = db;
            _topicService = topicService;
            _service = service;
            _webHostEnvironment = webHostEnvironment;            
        }

        // GET: Stems
        [HttpGet]
        [ProducesResponseType(typeof(StemDto), 200)]
        public async Task<IActionResult> Index()
        {            
            return View(await _service.GetAll());
        }        

        // GET: Stems/Details/5
        [HttpGet]
        [ProducesResponseType(typeof(StemDto), 200)]
        public async Task<IActionResult> Details(int id)
        {
            MyDTO myDTO = await _service.Get(id);
            ViewBag.Message = myDTO.Message;
            if (myDTO.View == "Index")
            {
                return View($"{myDTO.View}", myDTO.StemDtos);
            }
            return View($"{myDTO.View}", myDTO.StemDto);
        }       

        // GET: Stems/Create
        [HttpGet]
        [ProducesResponseType(typeof(StemDto), 200)]
        public async Task<IActionResult> Create() 
        {
            ViewBag.Options = new List<SelectListItem>{
                new SelectListItem { Value = "A", Text = "A" },
                new SelectListItem { Value = "B", Text = "B" },
                new SelectListItem { Value = "C", Text = "C" },
                new SelectListItem { Value = "D", Text = "D" }
            };                        
            ViewBag.Topics = new SelectList(await _topicService.GetAll(), "Description", "Description");
            return View();
        }

        // POST: Stems/Create
        
        [HttpPost]
        [ProducesResponseType(typeof(StemDto), 200)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("Id,Question,OptionA,OptionB,OptionC,OptionD,CorrectAnswer,TopicDescription,Topic")] StemDto stemDto) 
        {
            MyDTO myDTO = await _service.AddOrUpdate(id, stemDto);
            ViewBag.Message = myDTO.Message;
            if (myDTO.View == "Index")
            {
                return View($"{myDTO.View}", myDTO.StemDtos);
            }
            return View($"{myDTO.View}", myDTO.StemDto);
        }

        // GET: Stems/Edit/5
        [HttpGet]
        [ProducesResponseType(typeof(StemDto), 200)]
        public async Task<IActionResult> Edit(int id) 
        {
            MyDTO myDTO = await _service.GetForUpdate(id);
            ViewBag.Message = myDTO.Message;
            ViewBag.Options = new List<SelectListItem>{
                new SelectListItem { Value = "A", Text = "A" },
                new SelectListItem { Value = "B", Text = "B" },
                new SelectListItem { Value = "C", Text = "C" },
                new SelectListItem { Value = "D", Text = "D" }
            };                                    
            ViewBag.Topics = new SelectList(await _topicService.GetAll(), "Description", "Description");
            if (myDTO.View == "Index")
            {
                return View($"{myDTO.View}", myDTO.StemDtos);
            }
            return View($"{myDTO.View}", myDTO.StemDto);
            
            
        }

        // POST: Stems/Edit/5
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ProducesResponseType(typeof(StemDto), 200)]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Question,OptionA,OptionB,OptionC,OptionD,CorrectAnswer,TopicDescription,Topic")] StemDto stemDto) 
        {
            MyDTO myDTO = await _service.AddOrUpdate(id, stemDto);
            ViewBag.Message = myDTO.Message;
            if (myDTO.View == "Index")
            {
                return View($"{myDTO.View}", myDTO.StemDtos);
            }
            return View($"{myDTO.View}", myDTO.StemDto);
        }

        // GET: Stems/Delete/5
        [HttpGet]
        [ProducesResponseType(typeof(StemDto), 200)]
        public async Task<IActionResult> Delete(int id) 
        {
            MyDTO myDTO = await _service.GetForDelete(id);
            ViewBag.Message = myDTO.Message;
            if (myDTO.View == "Index")
            {
                return View($"{myDTO.View}", myDTO.StemDtos);
            }
            return View($"{myDTO.View}", myDTO.StemDto);
        }

        // POST: Stems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [ProducesResponseType(typeof(StemDto), 200)]
        public async Task<IActionResult> DeleteConfirmed(int id) 
        {
            MyDTO myDTO = await _service.Delete(id);
            ViewBag.Message = myDTO.Message;
            return View($"{myDTO.View}", myDTO.StemDtos);
        }
    }
}

Sidebar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sidebar</title>

 <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/bootstrapDarkly.css"/>
    <link rel="stylesheet" href="~/css/dark.css" asp-append-version="true" />
    <link id="stylesheet" rel="stylesheet" href="~/css/light.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sidebar.styles.css" asp-append-version="true" />
    <script src="https://cdn.ckeditor.com/ckeditor5/35.4.0/classic/ckeditor.js"></script>    

<style>

        .container {
            max-width: 1280px;
            margin: 0 auto;
        }

        .sidenav {
            
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color:#222222;
            overflow-x: hidden;
            transition: 0.1s;
            padding-top: 60px;
            border-radius: 0 5px 5px 0;
        }

            .sidenav a {
                padding: 8px 8px 8px 32px;
                text-decoration: none;
                font-size: 20px;
                color: white;
                transition: 0.3s;
                text-align:left;
                margin-left: 18px;
            }

                .sidenav a:hover {
                    color: white;
                }


        #main {
            transition: margin-left .5s;
            padding: 16px;
        }

        .typing-text {
  text-shadow: 2px 2px 2px #333;
}
  
</style>
</head>
<body>

 <div class="  container">
   <nav class=" bg-primary">
      <div id="mySidenav" class="sidenav">
        <ul class="navbar-nav flex-grow-1">
            <li>
                   <button class="button-nav" onclick="toggleNav()">
                    <span class="icon">
                    <svg viewBox="0 0 175 80" width="40" height="40">
                    <rect width="80" height="15" fill="#f0f0f0" rx="10"></rect>
                    <rect y="30" width="80" height="15" fill="#f0f0f0" rx="10"></rect>
                    <rect y="60" width="80" height="15" fill="#f0f0f0" rx="10"></rect>
                    </svg>
                    </span>
                    <span class="text">MENU</span>
                    </button>
            </li>
                  
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Candidates" asp-action="Index">Candidates</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Certificates" asp-action="Index">Certificates</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Topics" asp-action="Index">Topics</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Stems" asp-action="Index">Stems</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="ExamStems" asp-action="Index">ExamStems</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Exams" asp-action="Index">Exams(index)</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Exams" asp-action="Create">Exams(Create)</a>
            </li>
            <li>
                      
                        <label class="switch">
                            <input type="checkbox" id="togBtn" onclick="myFunction()">
                            <div class="slider round"></div>
                        </label>

                       
            </li>
           @* <li>
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">

            </li>
            <li>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </li>*@
        </ul>

     </div>
  </nav>
</div>
    <div id="main">

       @* <span class="sticky-header" style=" font-size:30px;cursor:pointer " onclick="toggleNav()">&#9776;  &nbsp </span>*@
      @*  <button class="btn" onclick="toggleNav()">
            <span class="icon">
                <svg viewBox="0 0 175 80" width="40" height="40">
                    <rect width="80" height="15" fill="#f0f0f0" rx="10"></rect>
                    <rect y="30" width="80" height="15" fill="#f0f0f0" rx="10"></rect>
                    <rect y="60" width="80" height="15" fill="#f0f0f0" rx="10"></rect>
                </svg>
            </span>
            <span class="text">MENU</span>
        </button>*@
        
</div>
   

    <div class=" container ">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   


   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>
</html> 

    
   